CREATE SCHEMA IF NOT EXISTS ACL_EPRIVACY_CONSENT;

CREATE TABLE IF NOT EXISTS ACL_EPRIVACY_CONSENT.EPRIVACY_CONSENT (
    DATASUBJECT_ID      VARCHAR(255),
    PURPOSE_ID          VARCHAR(255),
    VIN                 VARCHAR(255),
    PURPOSE_NAME        VARCHAR(255),
    PURPOSE_STATUS      VARCHAR(50),
    PURPOSE_DATE        TIMESTAMP,
    PURPOSE_VERSION     VARCHAR(50),
    PURPOSE_GLOBAL_CODE VARCHAR(255),
    PANE_PURPOSE_NAME   VARCHAR(255),
    UNIFIED_CUSTOMER_ID VARCHAR(255),
    PORTAL_UUID         VARCHAR(255),
    BRAND               VARCHAR(100),
    NMSC_CODE           VARCHAR(100),
    COUNTRY_CODE        VARCHAR(10),
    SOURCE_SYSTEM_NAME  VARCHAR(255),
    LANGUAGE            VARCHAR(10),
    DELETE_FLAG         VARCHAR(5),
    DELETE_DATE          TIMESTAMP,
    CREATED_DATE         TIMESTAMP,
    UPDATED_DATE         TIMESTAMP,
    PRIMARY KEY (DATASUBJECT_ID, PURPOSE_ID, VIN)
);
